Simplify & Improve Carbon Client
openflighthpc/carbon-leaderboard pull request #12
Opened 2024-04-29 09:01 UTC by ColonelPanicks

This PR aims to improve the simplicity of the carbon client script and improve on the usage and documentation.

- Corrects documentation to show that script is sending system info, not carbon data, to the leaderboard 
- Removes unnecessary/hangover parts of the program (reporting info on the CLI) so the script is only a companion to the leaderboard
- Add variable for specifying the command to run (to support running via `curl`) 
- Document all the variables in the help output of the script 
- Adds the ability to force offline mode 
- Improves handling of LOCATION in various scenarios (offline mode, interactive/non-interactive, etc)

2024-04-29 09:04 UTC, ColonelPanicks commented
Rebased on `dev/0.0.3` with fixes to conflicts.

2024-04-29 16:29 UTC, Womblue approved these changes
LGTM! It's a shame that we couldn't quite remove Boavizta from the script entirely, but it's nice to see the script be so much lighter.

2024-05-01 11:50 UTC, Womblue requested changes
One minor improvement I'd recommend, otherwise LGTM

2024-05-01 11:50 UTC, Womblue commented on carbon-client/carbon
> +        echo "Upload $PAYLOAD_FILE to $LEADERBOARD_URL to get your carbon calculations."
Could change this to `$LEADERBOARD_URL/data-entry` to point users directly to the new data entry page.

2024-05-01 13:44 UTC, merged